name: Quantum Random Bit Generator CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test
        run: |
          dotnet build --no-restore --configuration Release QuantumRandomBitGenerator.csproj
          dotnet publish --no-build --configuration Release --output bin/Release/net6.0 QuantumRandomBitGenerator.csproj
          dotnet test --no-build --verbosity normal QuantumRandomBitGenerator.csproj

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set time
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag quantum-random-bit-generator --build-arg TIMESTAMP=$TIMESTAMP --input path=.

      - name: Run Docker container
        run: docker run quantum-random-bit-generator

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: GitHub Container Registry login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository }}:latest --push .

  save-artifact:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: quantum-random-bit-generator
          path: /home/runner/work/QuantumRandomBitGenerator/QuantumRandomBitGenerator/bin/Release/net6.0/QuantumRandomBitGenerator.dll
