name: Quantum Random Bit Generator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal QuantumRandomBitGenerator.csproj

    - name: Set time
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag quantum-random-bit-generator --build-arg TIMESTAMP=$TIMESTAMP --input path=.

    - name: Run Docker container
      run: docker run quantum-random-bit-generator
    
  
  save-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      
      with:
        name: quantum-random-bit-generator
        path: /home/runner/work/QuantumRandomBitGenerator/QuantumRandomBitGenerator/bin/Debug/net6.0/QuantumRandomBitGenerator.dll
